// -----------------------------------------------------------------------------
/*
  Use a Micro SD Card Module to save and load binary 8080 machine language programs.

  The arrry, theProgram, is a binary 8080 machine language program.
  Write it to the SD card.
  Read it from the SD card and compare it with the original array.

  SPI reference: https://www.arduino.cc/en/Reference/SPI
  SD card library reference: https://www.arduino.cc/en/reference/SD
*/
// -----------------------------------------------------------------------------
// SD Card module uses SPI.

#include <SPI.h>
#include <SD.h>

// SD Card Module is an SPI slave device.
//  CS (chip/slave select)     to Nano pin 10 (SS pin). Can be any digital pin on the master(Nano) to enable and disable this device on the SPI bus.
// SCK, MOSI, MISO are the SPI hardware pins are declared in the SPI library.
//  SCK (serial clock)         to Nano pin 13 SPI: accepts clock pulses which synchronize data transmission generated by Arduino
//  MOSI (master out slave in) to Nano pin 11 SPI: input to the Micro SD Card Module.
//  MISO (master in slave Out) to Nano pin 12 SPI: output from the Micro SD Card Module.
//  VCC (3.3V or 5V)           to Nano pin 5V+
//  GND (ground)               to Nano pin ground

// The CS pin is the only one that is not really fixed as any of the Arduino digital pin.
const int csPin = 10;  // SD Card module is connected to Nano pin 10.
File myFile;

// Test file name.
// Files are created using uppercase: F1.TXT.
String theFilename = "f1.txt";

// -----------------------------------------------------------------------------
// Test program to use in this program. The program tests the 16 bit add opcode, dad.

byte theProgram[] = {
  //                //            ; --------------------------------------
  //                //            ; Test opcode dad.
  //                //            ; --------------------------------------
  //                // Start:     ; Intialize register values.
  B00111110, 6,     // mvi a,6    ; Move numbers to registers.
  B00000110, 0,     // mvi b,0
  B00001110, 1,     // mvi c,1
  B00010110, 2,     // mvi d,2
  B00011110, 3,     // mvi e,3
  B00100110, 4,     // mvi h,0
  B00101110, 5,     // mvi l,0
  0343, 38,         // out 38     ; Print the Intialized register values.
  //                //            ; --------------------------------------
  //0RP1001
  B00001001,        // dad b      ; Add register pair B:C to H:L.
  0343, 36,         // out 36     ; Print register pair, H:L.
  B00011001,        // dad d      ; Add register pair D:E to H:L.
  0343, 36,         // out 36     ; Print register pair, H:L.
  //                //            ; --------------------------------------
  0166,             // hlt
  0303, 0000, 0000, // jmp Start  ; Jump back to beginning.
  0000              //            ; End.
};

// -----------------------------------------------------------------------------
// Memory definitions

const int memoryBytes = 256;
byte memoryData[memoryBytes];
unsigned int programCounter = 0;     // Program address value

// -----------------------------------------------------------------------------
// Memory Functions

char charBuffer[17];
byte zeroByte = B00000000;

void initMemoryToZero() {
  Serial.println(F("+ Initialize all memory bytes to zero."));
  for (int i = 0; i < memoryBytes; i++) {
    memoryData[i] = zeroByte;
  }
}

void copyByteArrayToMemory(byte btyeArray[], int arraySize) {
  Serial.println(F("+ Copy the program into the computer's memory array."));
  for (int i = 0; i < arraySize; i++) {
    memoryData[i] = btyeArray[i];
  }
  Serial.println(F("+ Copied."));
}

void listByteArray(byte btyeArray[], int arraySize) {
  Serial.println(F("+ List the program."));
  Serial.println(F("++   Address:       Data value"));
  for (int i = 0; i < arraySize; i++) {
    Serial.print(F("+ Addr: "));
    sprintf(charBuffer, "%4d:", i);
    Serial.print(charBuffer);
    Serial.print(F(" Data: "));
    printData(btyeArray[i]);
    Serial.println("");
  }
  Serial.println(F("+ End of listing."));
}

// -----------------------------------------------------------------------------
// Output: log messages and Front Panel LED data lights.

void printByte(byte b) {
  for (int i = 7; i >= 0; i--)
    Serial.print(bitRead(b, i));
}
void printWord(int theValue) {
  String sValue = String(theValue, BIN);
  for (int i = 1; i <= 16 - sValue.length(); i++) {
    Serial.print("0");
  }
  Serial.print(sValue);
}

void printOctal(byte b) {
  String sOctal = String(b, OCT);
  for (int i = 1; i <= 3 - sOctal.length(); i++) {
    Serial.print("0");
  }
  Serial.print(sOctal);
}

void printData(byte theByte) {
  sprintf(charBuffer, "%3d = ", theByte);
  Serial.print(charBuffer);
  printOctal(theByte);
  Serial.print(F(" = "));
  printByte(theByte);
}

// -----------------------------------------------------------------------------
// Write Program memory to a file.

void writeProgramMemoryToFile(String theFilename) {
  Serial.println("+ Write program memory to a new file named: ");
  Serial.print(theFilename);
  Serial.println("+ Check if file exists. ");
  if (SD.exists(theFilename)) {
    SD.remove(theFilename);
    Serial.println("++ Exists, so it was deleted.");
  } else {
    Serial.println("++ Doesn't exist.");
  }
  myFile = SD.open(theFilename, FILE_WRITE);
  if (!myFile) {
    Serial.print("- Error opening file: ");
    Serial.println(theFilename);
    return; // When used in setup(), causes jump to loop().
  }
  Serial.println("++ New file opened.");
  Serial.println("++ Write binary memory to the file.");
  for (int i =0; i < memoryBytes; i++) {
    myFile.write(memoryData[i]);
  }
  myFile.close();
  Serial.println("+ Completed, file closed.");
}

// -----------------------------------------------------------------------------
// Open and read a file.

byte fileMemoryData[memoryBytes];

void readProgramFileIntoMemory(String theFilename) {
  Serial.println("+ Read a file into program memory, file named: ");
  Serial.print(theFilename);
  Serial.println("+ Check if file exists. ");
  if (SD.exists(theFilename)) {
    Serial.println("++ Exists, so it can be read.");
  } else {
    Serial.println("++ Doesn't exist, cannot read.");
    return;
  }
  myFile = SD.open(theFilename);
  if (!myFile) {
    Serial.print("- Error opening file: ");
    Serial.println(theFilename);
    return;
  }
  int i = 0;
  while (myFile.available()) {
    // Reads one character at a time.
    fileMemoryData[i] = myFile.read();
    // Print Binary:Octal:Decimal values.
    Serial.print("B");
    printByte(fileMemoryData[i]);
    Serial.print(":");
    printOctal (fileMemoryData[i]);
    Serial.print(":");
    Serial.println(fileMemoryData[i], DEC);
    i++;
    if (i > memoryBytes) {
      Serial.println("-+ Warning, file contains more data bytes than abailable memory.");
    }
  }
  myFile.close();
  Serial.println("+ File closed.");
}

// -----------------------------------------------------------------------------
void setup() {
  Serial.begin(115200);
  // Give the serial connection time to start before the first print.
  delay(1000);
  Serial.println(""); // Newline after garbage characters.
  Serial.println("+++ Setup.");

  // ----------------------------------------------------
  // Note, csPin is optional. The default is the hardware SS line (pin 10) of the SPI bus.
  // If using pin, other than 10, add: pinMode(otherPin, OUTPUT);
  // The pin connected to the chip select pin (CS) of the SD card.
  if (!SD.begin(csPin)) {
    Serial.println("- Error initializing SD card.");
    return; // When used in setup(), causes jump to loop().
  }
  Serial.println("+ SD card initialized.");

  // ----------------------------------------------------
  int programSize = sizeof(theProgram);
  // List a program.
  listByteArray(theProgram, programSize);
  // Load a program.
  copyByteArrayToMemory(theProgram, programSize);

  // Write the file to the SD card.
  // writeProgramMemoryToFile("dad.asm");

  // Read the SD card file data into an array.
  readProgramFileIntoMemory("dad.asm");
  // comparedProgramFileIntoMemory();

  // ----------------------------------------------------
  Serial.println("+++ Go to loop.");
}

// -----------------------------------------------------------------------------
// Device Loop
void loop() {
  Serial.println("+ Looping");
  delay(10000);
}
// -----------------------------------------------------------------------------
